version: 2
updates:
  # 1. Surveille les dépendances Gradle (Android, libs Java/Kotlin, etc.)
  - package-ecosystem: "gradle"
    directory: "/"          # surveille les fichiers gradle à la racine
    schedule:
      interval: "monthly"    # vérifie une fois par semaine
    open-pull-requests-limit: 5
    reviewers:
      - "@brubbs77" # optionnel : t'assigne directement comme reviewer

  # 2. Surveille aussi les GitHub Actions (workflows CI/CD)
  - package-ecosystem: "github-actions"
    directory: "/"          # surveille le dossier .github/workflows/
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "@brubbs77"
