name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2️⃣ Installer JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # 3️⃣ Rendre gradlew exécutable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4️⃣ Build APK Debug
      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon

      # 5️⃣ Uploader l'APK
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
